### ISSUE TITLE
FYI https://ni55an.github.io/allmatter seems to not load.

### ISSUE THREAD

**Issue by follower** [Ni55aN/allmatter#1]
Seems to have many 404 errors?

**Comment by Ni55aN** [comment]
I deployed on Github Pages 6 days ago and everything worked. 

Perhaps this is a problem in the GH Pages themselves

**Comment by follower** [comment]
Does it work for you currently?

There appear to be multiple issues:

 * <https://rawgit.com/eligrey/FileSaver.js/master/FileSaver.min.js> is 404, a potentially working alternative is to use <https://cdn.rawgit.com/eligrey/FileSaver.js/1.3.4/FileSaver.min.js>. This seems to be a build issue with the original project, see: https://github.com/eligrey/FileSaver.js/issues/436 &  https://github.com/eligrey/FileSaver.js/issues/433

* <https://ni55an.github.io/allmatter/common.js> is 404.

* <https://ni55an.github.io/allmatter/splash.js> is 404. (However <https://ni55an.github.io/allmatter/src/splash.js> does exist.)

 * <https://ni55an.github.io/allmatter/%3C%=%20require('./logo.svg')%20%%3E> is (understandably) 400 but I assume that's related to something else not loading correctly?

It seems like maybe the source repository (rather than build output?) is in the `gh-pages` branch or something?

Anyway, all FYI. :)

**Comment by Ni55aN** [comment]
I have updated html-webpack-plugin and now webpack successfully creates all the bundles, but GitHub Pages are not updated after building on Travis
https://travis-ci.org/Ni55aN/allmatter/builds/367890320#L453
